name: intray-cli
version: '0.0.0.0'
synopsis: A command line interface for the intray app.
description: Please see README.md
category: Intray
author: Tom Sydney Kerckhove & Nick Van den Broeck
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray-cli

library:
  source-dirs: src/
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude
  exposed-modules:
  - Intray.Cli
  - Intray.Cli.LastSeen
  - Intray.Cli.OptParse
  - Intray.Cli.Session
  - Intray.Cli.Store
  - Intray.Cli.Sync

  dependencies:
  - base >=4.9 && <5
  - aeson >=1.0
  - aeson-pretty >=0.8
  - bytestring >=0.10
  - cookie >=0.4
  - http-client >=0.5
  - http-client-tls >=0.3
  - intray-api
  - intray-client
  - intray-data
  - optparse-applicative >=0.13
  - path >=0.4
  - pretty-relative-time
  - mtl >=2.2
  - path-io >=1.2
  - servant >=0.9
  - servant-auth-client >=0.2
  - servant-auth-server >=0.3
  - servant-client >=0.9
  - servant-server >=0.9
  - validity
  - text >=1.2
  - time
  - yaml >=0.8

executables:
  intray:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - intray-cli

tests:
  intray-cli-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bytestring
    - genvalidity-hspec
    - genvalidity-hspec-aeson >=0.1
    - hspec
    - intray-cli
    - intray-client
    - intray-data
    - intray-server-test-utils
    - mtl
    - path
    - path-io
    - servant
    - servant-client
    - text >=1.2
