name: intray-api
version: '0.0.0.0'
synopsis: Intray API
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray
default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Intray.API
  - Intray.API.Admin
  - Intray.API.Admin.Types
  - Intray.API.Protected
  - Intray.API.Protected.AccessKey
  - Intray.API.Protected.AccessKey.Types
  - Intray.API.Protected.Account
  - Intray.API.Protected.Account.Types
  - Intray.API.Protected.Item
  - Intray.API.Protected.Item.Types
  - Intray.API.Types
  dependencies:
  - aeson
  - base >=4.7 && <5
  - base64-bytestring
  - blaze-html
  - blaze-markup
  - bytestring >=0.10 && <0.11
  - containers
  - cookie
  - intray-data
  - mergeless
  - servant
  - servant-auth
  - servant-auth-docs
  - servant-auth-server
  - servant-blaze
  - servant-docs
  - text
  - time
  - typed-uuid
  - uuid >=1.3 && <1.4
  - validity >=0.4
  - validity-bytestring >=0.2
  - validity-containers
  - validity-text >=0.2
  - validity-time >=0.1
  - validity-uuid >=0.0
