name: intray-server-test-utils
version: '0.0.0.0'
synopsis: Test utils for intray-server
description: Please see README.md
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray-server

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Intray.Server.TestUtils
  default-extensions:
  - NoImplicitPrelude

  dependencies:
  - QuickCheck >=2.9
  - base
  - bytestring >=0.10 
  - cookie >=0.4
  - containers
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-hspec
  - genvalidity-mergeless
  - genvalidity-text
  - genvalidity-time
  - hspec
  - http-client
  - http-types
  - intray-api
  - intray-client
  - intray-data
  - intray-data-gen
  - intray-server
  - microlens >=0.4
  - monad-logger
  - path
  - path-io
  - persistent-sqlite
  - resourcet
  - servant
  - servant-auth-client
  - servant-auth-server
  - servant-client
  - servant-server
  - text >=1.2
  - typed-uuid
  - wai
  - warp

tests:
  intray-server-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - base >=4.9 && <5
    - bytestring
    - genvalidity-bytestring
    - genvalidity-hspec
    - genvalidity-text
    - genvalidity-time
    - hspec
    - http-types
    - intray-api
    - intray-api-gen
    - intray-client
    - intray-data
    - intray-data-gen
    - intray-server-test-utils
    - path
    - path-io
    - servant
    - servant-client
    - text

benchmarks:
  intray-server-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - QuickCheck
    - base
    - bytestring
    - cookie
    - criterion
    - intray-client
    - servant
    - servant-auth-client
    - servant-client
    - intray-server-test-utils
